name: Deploy site

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: 'Checkout default branch to $GITHUB_WORKSPACE dir'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
         cosign-release: 'v1.13.1'

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         tags: type=sha,format=long

      - name: Build and Push container images
        uses: docker/build-push-action@v3.2.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - uses: sigstore/cosign-installer@main
        with:
         cosign-release: 'v1.13.1'

      - name: Sign the container image
        env:
         TAGS: ${{ steps.docker_meta.outputs.tags }}
         COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${TAGS} --force
        
